# Generated by Django 3.0.4 on 2020-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200504_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='docs',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Add a document'),
        ),
    ]
